name: Build SunamoSelenium

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoSelenium
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoSelenium/SunamoSelenium.csproj

    - name: Build
      run: dotnet build SunamoSelenium/SunamoSelenium.csproj --configuration Release --no-restore

  test:
    name: Test SunamoSelenium.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoSelenium.Tests/SunamoSelenium.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoSelenium.Tests/SunamoSelenium.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoSelenium.Tests/SunamoSelenium.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
